onlyBuiltDependencies:
    - better-sqlite3
    - esbuild
catalog:
    vite: npm:@voidzero-dev/vite-plus-core@latest
    vitest: npm:@voidzero-dev/vite-plus-test@latest
    vite-plus: latest
overrides:
    vite: 'catalog:'
    vitest: 'catalog:'
peerDependencyRules:
    allowAny:
        - vite
        - vitest
    allowedVersions:
        vite: '*'
        vitest: '*'
allowBuilds:
    better-sqlite3: true
    esbuild: true
    fallow: true
    unrs-resolver: true
